### ISSUE TITLE
连线内数字会被遮挡

### ISSUE THREAD

**Issue by AtticusLv** [findyourmagic/dber#16]
![image](https://user-images.githubusercontent.com/22365371/180710117-7727643f-557e-4e6f-a556-6cb09ab35a22.png)

如上图，如果拖拽位置不佳，连线数字会被遮挡。

btw，已star，感谢好用的在线工具👍

**Comment by findyourmagic** [comment]
感谢，后面会根据位置关系用不同的曲线类型连接，尽量减少遮挡。

**Comment by 280code** [comment]
![image](https://user-images.githubusercontent.com/63572275/187595055-939956fa-1632-4770-9a17-06f8b7009a5d.png)
![image](https://user-images.githubusercontent.com/63572275/187595118-a2d63005-3851-49ce-9618-835437086281.png)
![image](https://user-images.githubusercontent.com/63572275/187595155-34d4fb0c-e290-49c4-83f2-7021e50f1635.png)
![image](https://user-images.githubusercontent.com/63572275/187595183-e013533b-9742-4c39-985a-a261257b3d3d.png)
编辑表格，增加字段，此时type值的空的，直接点提交会提示，然后选择type值之后再提交，便无反应。
意思是说，增加字段时如果没有选择type值就提交，后面就无法提交了，更改也无法保存，只能重来，只能重来啊！！！
