### ISSUE TITLE
导出sql中的pgsql的bigint 数据类型问题

### ISSUE THREAD

**Issue by jackman0925** [findyourmagic/dber#24]
导出sql中的pgsql的bigint 数据类型问题 ，请见附件
<img width="1015" alt="DBER1_png_and_DBER" src="https://user-images.githubusercontent.com/2059376/188544455-7eaeee25-106e-43a6-8fd2-94e4e6a353fc.png">

**Comment by findyourmagic** [comment]
感谢，
PG 里面设置自增的 bigint 做主键时好像需要设置为 bigserial，当前的问题可以先把类型设置为 bigserial 解决。
不过确实这里直接转换成 serial 是有问题的，这个转换的问题源自所依赖的库 dbml，我会再测试下给他们提个 issue，并在这里跟进一下结果。

**Comment by jackman0925** [comment]
👍，online的已经很不错了，加油！
提一个建议, 如果表多的话查找不是很方便，如果左手边有一个列表会更加方便一些，谢谢!

**Comment by findyourmagic** [comment]
类似索引可以快速聚焦到指定表那种么？不错的建议
