### ISSUE TITLE
导入导出的时候显示loading时间特别长，很少有成功的时候，看您的示例网站上也是这样

### ISSUE THREAD

**Issue by maker997** [findyourmagic/dber#34]

**Comment by findyourmagic** [comment]
这个还挺少见的，感觉可能是兼容性问题，是用的 chrome 或者 edge 么？
可以多提供一些信息方便进一步排查

**Comment by maker997** [comment]
我这个解决了。当时我用的chrome版本123.0.6312.106。收到回复后我换了edge浏览器就好了，在换回chrome也没有这个问题了。非常感谢
