### ISSUE TITLE
npm run dev 时报错，是版本问题么？

### ISSUE THREAD

**Issue by cxandph** [findyourmagic/dber#6]
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Not supported
    at Object.loadConfig [as default] (E:\CodeResearchFront\dber\node_modules\next\dist\server\config.js:68:78)
    at async NextServer.loadConfig (E:\CodeResearchFront\dber\node_modules\next\dist\server\next.js:114:22)
    at async NextServer.prepare (E:\CodeResearchFront\dber\node_modules\next\dist\server\next.js:96:24)
    at async E:\CodeResearchFront\dber\node_modules\next\dist\cli\next-dev.js:127:9
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! db-graph@ dev: `next dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the db-graph@ dev script.

**Comment by iqiql** [comment]
用yarn dev启动吧，我用npm启动之后报了个语法错误，可能是npm install的时候少了crypto这个包，用yarn install 然后yarn dev就可以了，期待作者的后续更新~

**Comment by findyourmagic** [comment]
@cxandph 
node版本是什么？node v16.13.1 下暂时没有复现这个问题

**Comment by findyourmagic** [comment]
暂时先关闭了，如果还是有问题可以附带一下版本信息

**Comment by yanxiaochuan** [comment]
node v12.18.2 启动报错

**Comment by findyourmagic** [comment]
@yanxiaochuan 感谢提出问题。
应该是 next.js 不支持 v12 了，目前项目里 .node-version 文件指定的版本是 v16.13.1，可以升级一下 node 版本或者用 nvm 之类的多版本工具试试。
