### ISSUE TITLE
不支持加注释和不能显示类型指定长度

### ISSUE THREAD

**Issue by itanag** [findyourmagic/dber#9]
没有这两个功能感觉应用挺鸡肋的

**Comment by findyourmagic** [comment]
指定长度是可以的，在那个类型下拉框里不要选择，直接输入括号和类型长度然后回车，这里体验随后会优化下。
注释具体指的的是哪部分的注释？

**Comment by findyourmagic** [comment]
@itanag 
指定长度是可以的，在那个类型下拉框里不要选择，直接输入类型加括号和类型长度然后回车，这里体验随后会优化下。
eg: VARCHAR(16) 然后回车

注释具体指的的是哪部分的注释？

**Comment by litgh** [comment]
他说的应该是字段注释. 另外编辑字段的UI过于复杂..字段一多的话上下拉很麻烦.. 用table的形式组织字段会好点

**Comment by chqa** [comment]
首先感谢作者 这个项目挺好的
长度 我单独加了个  
另外默认值原来的有点错误  生成的是undefined 我也改了一下  
希望作者可以继续维护这个项目

**Comment by findyourmagic** [comment]
@chqa 感谢支持，你更新的部分可以提交PR合并到项目里来。
这个项目会继续维护的，受限于能投入的时间，可能维护频率不会太高。

**Comment by findyourmagic** [comment]
现在添加长度已经进行了优化，直接在输入框内添加，比如：VARCHAR(16) 即可
